<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>ST7 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\s*;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(#\s*include)\s+(".*")\s*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\s*(segment)\s+(byte\s+)?('.*')</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(TITLE|AUTHOR|DESCRIPTION)\s+(".*")\s*$</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(MOTOROLA|WORDS|BYTES)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[\t](\.bell|byte|cequ|\.ctrl|date|d(c|s)\.(b|w|l)|#define|end|equ|extern|#else|#endif|fcs|\.form|group|#if[12b]?|#ifidn|#ifdef|#iflab|intel|\.lall|\.list|#load|local)\b</string>
			<key>name</key>
			<string>keyword.mnemonic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[\t](adc|add|and|bcp|bres|bset|btjf|btjt|call|callr|clr|cp|cpl|dec|halt|inc|iret|jp|jr(a|t|f|ih|il|h|nh|m|nm|mi|pl|eq|ne|c|nc|ult|uge|ugt|ule)|ld|mul|neg|nop|or|pop|push|rcf|ret|rim|rlc|rrc|rsp|sbc|scf|sim|sla|sll|sra|sub|swap|tnz|trap|wfi|xor)\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*([a-zA-Z0-9_]+)\s(ds\.(b|w|l))\s+([0-9]+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*([a-zA-Z0-9_]+)\s(dc\.(b|w|l))\s+</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[a-zA-Z0-9_]+:?</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#)([0-9]+|(\$)[0-9A-F]+|(%)[01]+)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(\$)([0-9a-f]+)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b(%)([01]+)\b</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(a|b|x)+\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm</string>
	<key>uuid</key>
	<string>00DDB367-0875-4FF3-8047-D3FF2988B300</string>
</dict>
</plist>
